language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

go_import_path: github.com/mrosset/via

sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - env | grep TRAVIS
  - make
  - make test
