#+TITLE TODO's

#+STARTUP: showall

* TODO When packaging check PREFIX is honored
  We should check the sanity of PKGDIR. 

  We only record files in our manifest not directories. so
  an empty directory can end up in our tarball. But not be listed in the
  manifest this means we could try to untar a directory outside of our PREFIX.

  We'll have to check the total entries in each of these directories

1. PKGDIR
2. /usr
3. /usr/local
* TODO Via initialization
  When we first run via, it is dependent on the plans git repo for meta data.
  currently we git clone recursive the via repo, which contains the plans repo
  as well. We also do not respect the user and just blindly clone it on first run.

** TODO Create an init via function
  do not assume and fetch the plans repository. Error gracefully and suggest
  user to init the plans repo. 

* TODO Rework Test's
  Test should only handle input's and output's. Many of the test's right now
  simple invoke function's and test for go error's.

** TODO Add test for long link
   on macos when building emacs archive packages fails when nextstep is enabled

* TODO Build package in a sandbox.
  currently we are starting to build packages in a docker container. but this is 
  not automated we need to manually spin up the container and then interactively
  build packages.

  we should have a simple mechanism to build package in a container.
